# [Info]
site_name: 月全食的笔记本
site_url: https://eclipseyue.github.io
site_author: 月全食
site_keywords: 月全食, 个人网站, 个人博客, 个人笔记, 个人文档
site_description: 个人网站文档

# [Navigation]
nav:
  - 个人:
    - 个人介绍: ME/profile.md
  
  - 项目:
    - 项目: Project/Projects.md

  - 课程:
    - 课程: Course/Course_asm.md

  - 笔记:
    - 笔记导航: Note/Index.md
    - 编译原理: Note/Complie.md

  - 开发:
    - 开发学习: Dev/Dev.md

  - 美赛:
    - 美赛1: MCM/MCM.md
    - 美赛2: MCM/MCM2.md

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
  - md_in_html

plugins:
  - search


