# [Info]
site_name: 月全食的笔记本
site_url: https://eclipseyue.github.io
site_description: 个人网站文档

# [Navigation]
nav:
  - 个人:
    - 个人介绍: ME/profile.md
  
  - 笔记:
    - 笔记导航: Note/index.md
    - 编译原理: 
      - 课程笔记: Note/compile.md

  - 数学:
    - 数学导航: Math/index.md
    - 微积分:
      - 微积分: Math/calculus/calculus.md
    - 线性代数:
      - 线性代数: Math/linear_algebra/linear_algebra.md
    - 概率论:
      - 概率论: Math/probability/probability.md
  - AI:
    - AI导航: AI/index.md
    - 机器学习:
      - 机器学习: AI/machine_learning/machine_learning.md
    - 深度学习:
      - 深度学习: AI/deep_learning/deep_learning.md
    - 自然语言处理:
      - 自然语言处理: AI/nlp/nlp.md
    - 计算机视觉:
      - 计算机视觉: AI/cv/cv.md
    - 强化学习:
      - 强化学习: AI/reinforcement_learning/reinforcement_learning.md
    - 其他:
      - 其他: AI/other/1.md
    


  - CS:
    - CS导航: CS/index.md
    - 数据结构:
      - 数据结构: CS/data_structure/data_structure.md
    - 计算机组成原理:
      - 计算机组成原理: CS/computer_organization/computer_organization.md
    - 操作系统:
      - 操作系统: CS/operating_system/operating_system.md
    - 计算机网络:
      - 计算机网络: CS/computer_network/computer_network.md

  - 论文:
    - 论文导航: Paper/index.md
    - 论文笔记: Paper/paper.md

  - 技术:
    - 25秋招记录: Tech/25fall_recruitment_record.md
    - 简历复习: Tech/resume_review.md
    - 算法学习: Tech/alg_learn.md
    - C++八股: Tech/cpp_baguette.md
    - Java: Tech/java_path.md
    - 力扣记录: Tech/leetcode_record.md
    - record: Tech/record.md
    - STL容器: Tech/stl_cheatsheet.md

  - 生活:
    - 生活导航: Life/index.md
    - 健康管理: Life/health.md
    - 音乐学习: Life/music.md

theme:
  name: material
  # icon:
  #   logo: assets/favicon.jpg      # 网站图标
  #   repo: assets/favicon.jpg        # 仓库图标

  favicon: assets/favicon.jpg      # 网站图标
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections

  # 导航栏设置
  nav_style: dark          # 导航栏样式
  collapse_navigation: true # 折叠导航
  sticky_navigation: true  # 固定导航
  

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.emoji

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search


