# [Info]
site_name: 月全食的笔记本
site_url: https://eclipseyue.github.io
site_description: 个人网站文档

# [Navigation]
nav:
  - 个人:
    - 个人介绍: ME/profile.md
  
  - 笔记:
    - 笔记导航: Note/index.md
    # - 编译原理: Note/complie.md

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - attr_list
  - md_in_html

plugins:
  - search


